In [3]:
import pandas as pd
import numpy as np
import os

In [4]:
os.chdir("..")

In [ ]:
df = pd.read_csv("./data/test/trainTitanic.csv")
df.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

In [4]:
filter_df = df.drop('Name', axis=1)
filter_df = filter_df.drop('Ticket', axis=1)
filter_df = filter_df.drop('Cabin', axis=1)

In [5]:
filter_df.head(20)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
5,6,0,3,male,NaN,0,0,8.4583,Q
6,7,0,1,male,54.0,0,0,51.8625,S
7,8,0,3,male,2.0,3,1,21.0750,S
8,9,1,3,female,27.0,0,2,11.1333,S
9,10,1,2,female,14.0,1,0,30.0708,C
10,11,1,3,female,4.0,1,1,16.7000,S
11,12,1,1,female,58.0,0,0,26.5500,S
12,13,0,3,male,20.0,0,0,8.0500,S
13,14,0,3,male,39.0,1,5,31.2750,S
14,15,0,3,female,14.0,0,0,7.8542,S
15,16,1,2,female,55.0,0,0,16.0000,S
16,17,0,3,male,2.0,4,1,29.1250,Q
17,18,1,2,male,NaN,0,0,13.0000,S
18,19,0,3,female,31.0,1,0,18.0000,S
19,20,1,3,female,NaN,0,0,7.2250,C

## Test Decision Tree Building

In [6]:
test_df = filter_df
test_df = test_df[test_df["Age"].notna()]
test_df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
885,886,0,3,female,39.0,0,5,29.1250,Q
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [7]:
test_df.columns.tolist()

['PassengerId',
 'Survived',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Embarked']

In [8]:
# Rearrange columns to make survived the last column
cols = test_df.columns.tolist()
cols = cols[0:1] + cols[2:] + cols[1:2]
cols

['PassengerId',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Embarked',
 'Survived']

In [9]:
test_df = test_df[cols]
test_df

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survived
0,1,3,male,22.0,1,0,7.2500,S,0
1,2,1,female,38.0,1,0,71.2833,C,1
2,3,3,female,26.0,0,0,7.9250,S,1
3,4,1,female,35.0,1,0,53.1000,S,1
4,5,3,male,35.0,0,0,8.0500,S,0
...,...,...,...,...,...,...,...,...,...
885,886,3,female,39.0,0,5,29.1250,Q,0
886,887,2,male,27.0,0,0,13.0000,S,0
887,888,1,female,19.0,0,0,30.0000,S,1
889,890,1,male,26.0,0,0,30.0000,C,1
890,891,3,male,32.0,0,0,7.7500,Q,0

In [10]:
# Convert categorical features to one hot encoding
sex_mapping = {'male': 0, 'female': 1}
embarked_mapping = {'S': 0, 'C': 1}

test_df['Sex'] = test_df['Sex'].map(sex_mapping)
test_df['Embarked'] = test_df['Embarked'].map(embarked_mapping)
test_df

     PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0              1       3    0  22.0      1      0   7.2500       0.0         0
1              2       1    1  38.0      1      0  71.2833       1.0         1
2              3       3    1  26.0      0      0   7.9250       0.0         1
3              4       1    1  35.0      1      0  53.1000       0.0         1
4              5       3    0  35.0      0      0   8.0500       0.0         0
..           ...     ...  ...   ...    ...    ...      ...       ...       ...
885          886       3    1  39.0      0      5  29.1250       NaN         0
886          887       2    0  27.0      0      0  13.0000       0.0         0
887          888       1    1  19.0      0      0  30.0000       0.0         1
889          890       1    0  26.0      0      0  30.0000       1.0         1
890          891       3    0  32.0      0      0   7.7500       NaN         0

[714 rows x 9 columns]

In [11]:
test_df = test_df.dropna()
test_df

     PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0              1       3    0  22.0      1      0   7.2500       0.0         0
1              2       1    1  38.0      1      0  71.2833       1.0         1
2              3       3    1  26.0      0      0   7.9250       0.0         1
3              4       1    1  35.0      1      0  53.1000       0.0         1
4              5       3    0  35.0      0      0   8.0500       0.0         0
..           ...     ...  ...   ...    ...    ...      ...       ...       ...
883          884       2    0  28.0      0      0  10.5000       0.0         0
884          885       3    0  25.0      0      0   7.0500       0.0         0
886          887       2    0  27.0      0      0  13.0000       0.0         0
887          888       1    1  19.0      0      0  30.0000       0.0         1
889          890       1    0  26.0      0      0  30.0000       1.0         1

[684 rows x 9 columns]

## Test with DecisionTree

In [12]:
from DecisionTree import DecisionTree

In [13]:
test1 = DecisionTree.DecisionTree(max_depth=5)
data_np = test_df.to_numpy(dtype=object)[:, 1:]

test1.build_tree(data=data_np)

In [14]:
data_np.shape[0]

684

In [15]:
test1.print_tree()

Feature 1 < 0.5
Left:
  Feature 2 < 9.5
  Left:
    Feature 3 < 2.5
    Left:
      Leaf: 1
    Right:
      Feature 2 < 3.5
      Left:
        Feature 2 < 2.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
      Right:
        Leaf: 0
  Right:
    Feature 0 < 1.5
    Left:
      Feature 2 < 53.0
      Left:
        Feature 5 < 25.9375
        Left:
          Leaf: 0
        Right:
          Leaf: 0
      Right:
        Feature 2 < 75.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
    Right:
      Feature 5 < 51.697900000000004
      Left:
        Feature 5 < 19.5
        Left:
          Leaf: 0
        Right:
          Leaf: 0
      Right:
        Feature 0 < 2.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
Right:
  Feature 0 < 2.5
  Left:
    Feature 2 < 2.5
    Left:
      Feature 0 < 1.5
      Left:
        Leaf: 0
      Right:
        Leaf: 1
    Right:
      Feature 5 < 28.85625
      Left:
        Feature 5 < 28.23125
        Left:
          Leaf: 1
        Right:
          Leaf: 0
      Right:
        Feature 4 < 1.5
        Left:
          Leaf: 1
        Right:
          Leaf: 1
  Right:
    Feature 5 < 20.799999999999997
    Left:
      Feature 2 < 7.0
      Left:
        Feature 5 < 10.7979
        Left:
          Leaf: 0
        Right:
          Leaf: 1
      Right:
        Feature 5 < 7.7
        Left:
          Leaf: 1
        Right:
          Leaf: 0
    Right:
      Feature 2 < 5.5
      Left:
        Feature 2 < 3.5
        Left:
          Leaf: 0
        Right:
          Leaf: 1
      Right:
        Feature 4 < 4.5
        Left:
          Leaf: 0
        Right:
          Leaf: 0

In [16]:
test_pred = data_np[1:2,:]
test_pred

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1]], dtype=object)

In [17]:
test_pred.shape[0]

1

In [18]:
test_pred[0][3]

1

In [19]:
test1.predict_sample(test_pred)

1

In [20]:
test_preds = data_np[1:5,:]
test_preds

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1],
       [3, 1, 26.0, 0, 0, 7.925, 0.0, 1],
       [1, 1, 35.0, 1, 0, 53.1, 0.0, 1],
       [3, 0, 35.0, 0, 0, 8.05, 0.0, 0]], dtype=object)

In [21]:
test_preds

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0, 1],
       [3, 1, 26.0, 0, 0, 7.925, 0.0, 1],
       [1, 1, 35.0, 1, 0, 53.1, 0.0, 1],
       [3, 0, 35.0, 0, 0, 8.05, 0.0, 0]], dtype=object)

In [22]:
test_preds.shape

(4, 8)

In [23]:
test_preds[:, test_preds.shape[1]-1:]

array([[1],
       [1],
       [1],
       [0]], dtype=object)

In [24]:
test_preds[:, :test_preds.shape[1]-1]

array([[1, 1, 38.0, 1, 0, 71.2833, 1.0],
       [3, 1, 26.0, 0, 0, 7.925, 0.0],
       [1, 1, 35.0, 1, 0, 53.1, 0.0],
       [3, 0, 35.0, 0, 0, 8.05, 0.0]], dtype=object)

In [25]:
results = test1.predict(test_preds)
results

array([[1],
       [0],
       [1],
       [0]])

In [26]:
data_np

array([[3, 0, 22.0, ..., 7.25, 0.0, 0],
       [1, 1, 38.0, ..., 71.2833, 1.0, 1],
       [3, 1, 26.0, ..., 7.925, 0.0, 1],
       ...,
       [2, 0, 27.0, ..., 13.0, 0.0, 0],
       [1, 1, 19.0, ..., 30.0, 0.0, 1],
       [1, 0, 26.0, ..., 30.0, 1.0, 1]], dtype=object)

In [27]:
test_array = np.array([[]], dtype=object)
test_array

array([], shape=(1, 0), dtype=object)

In [28]:
test_array = np.empty(data_np.shape, dtype=object)
test_array

array([[None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       ...,
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None],
       [None, None, None, ..., None, None, None]], dtype=object)

In [29]:
for i in range(test_array.shape[0]):
    random_row = data_np[np.random.randint(data_np.shape[0])]
    test_array[i] = random_row

In [30]:
test_array

array([[2, 1, 34.0, ..., 23.0, 0.0, 1],
       [1, 1, 39.0, ..., 79.65, 0.0, 1],
       [2, 0, 19.0, ..., 36.75, 0.0, 0],
       ...,
       [1, 1, 60.0, ..., 75.25, 1.0, 1],
       [2, 1, 25.0, ..., 26.0, 0.0, 1],
       [1, 1, 58.0, ..., 153.4625, 0.0, 1]], dtype=object)

In [31]:
test_array

array([[2, 1, 34.0, ..., 23.0, 0.0, 1],
       [1, 1, 39.0, ..., 79.65, 0.0, 1],
       [2, 0, 19.0, ..., 36.75, 0.0, 0],
       ...,
       [1, 1, 60.0, ..., 75.25, 1.0, 1],
       [2, 1, 25.0, ..., 26.0, 0.0, 1],
       [1, 1, 58.0, ..., 153.4625, 0.0, 1]], dtype=object)

In [32]:
tree_bagger = DecisionTree.DecisionTree()

In [33]:
bagged_np = tree_bagger.perform_bagging(data_np)
bagged_np

array([[2, 1, 5.0, ..., 27.75, 0.0, 1],
       [3, 0, 4.0, ..., 27.9, 0.0, 0],
       [3, 0, 19.0, ..., 7.8958, 0.0, 0],
       ...,
       [3, 0, 24.5, ..., 8.05, 0.0, 0],
       [1, 0, 0.92, ..., 151.55, 0.0, 1],
       [3, 0, 38.0, ..., 7.8958, 0.0, 0]], dtype=object)

In [34]:
data_np_float = np.array(data_np, dtype=np.float64)
bagged_np_float = np.array(bagged_np, dtype=np.float64)

In [35]:
data_np_float.shape

(684, 8)

In [36]:
np.unique(data_np_float, axis=0).shape

(646, 8)

In [37]:
bagged_np_float.shape

(684, 8)

In [38]:
np.unique(bagged_np_float, axis=0).shape

(405, 8)

In [39]:
for i in range(0, 9):
    print(i)

0
1
2
3
4
5
6
7
8

In [40]:
data_np.shape

(684, 8)

In [41]:
data_np

array([[3, 0, 22.0, ..., 7.25, 0.0, 0],
       [1, 1, 38.0, ..., 71.2833, 1.0, 1],
       [3, 1, 26.0, ..., 7.925, 0.0, 1],
       ...,
       [2, 0, 27.0, ..., 13.0, 0.0, 0],
       [1, 1, 19.0, ..., 30.0, 0.0, 1],
       [1, 0, 26.0, ..., 30.0, 1.0, 1]], dtype=object)

In [42]:
# Randomly selecting features (application in Random Forest)
data_n = data_np.copy()
n_features = 3

if n_features < data_n.shape[1] - 1:
    data_n_labels = data_n[:,(data_n.shape[1]-1):data_n.shape[1]]
    data_n_data = data_n[:,:data_n.shape[1]-1]

    shuffled_indices = np.random.permutation(data_n_data.shape[1])
    data_n_data = data_n_data[:, shuffled_indices]
    data_n_data = data_n_data[:, :n_features]

    data_n = np.append(data_n_data, data_n_labels, axis=1)

data_n

array([[0.0, 22.0, 1, 0],
       [1.0, 38.0, 1, 1],
       [0.0, 26.0, 0, 1],
       ...,
       [0.0, 27.0, 0, 0],
       [0.0, 19.0, 0, 1],
       [1.0, 26.0, 0, 1]], dtype=object)

In [43]:
data_np.shape

(684, 8)

In [44]:
data_np[:, :3]

array([[3, 0, 22.0],
       [1, 1, 38.0],
       [3, 1, 26.0],
       ...,
       [2, 0, 27.0],
       [1, 1, 19.0],
       [1, 0, 26.0]], dtype=object)

In [45]:
np.append(data_np, data_np[:,7:8], axis=1)

array([[3, 0, 22.0, ..., 0.0, 0, 0],
       [1, 1, 38.0, ..., 1.0, 1, 1],
       [3, 1, 26.0, ..., 0.0, 1, 1],
       ...,
       [2, 0, 27.0, ..., 0.0, 0, 0],
       [1, 1, 19.0, ..., 0.0, 1, 1],
       [1, 0, 26.0, ..., 1.0, 1, 1]], dtype=object)

In [46]:
data_np[:,7:8]+data_np

array([[3, 0, 22.0, ..., 7.25, 0.0, 0],
       [2, 2, 39.0, ..., 72.2833, 2.0, 2],
       [4, 2, 27.0, ..., 8.925, 1.0, 2],
       ...,
       [2, 0, 27.0, ..., 13.0, 0.0, 0],
       [2, 2, 20.0, ..., 31.0, 1.0, 2],
       [2, 1, 27.0, ..., 31.0, 2.0, 2]], dtype=object)

In [47]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Shuffle columns
shuffled_indices = np.random.permutation(arr.shape[1])  # Generate random column indices
shuffled_arr = arr[:, shuffled_indices]  # Reorder columns

print("Original Array:\n", arr)
print("Shuffled Array:\n", shuffled_arr)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shuffled Array:
 [[ 2  3  1  4]
 [ 6  7  5  8]
 [10 11  9 12]]

In [48]:
set1Test = set(range(10))
set1Test

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [49]:
import random
random_element = random.choice(tuple(set1Test))
set1Test.remove(random_element)

In [50]:
set1Test

{0, 1, 2, 3, 4, 5, 6, 7, 8}

In [51]:
# test_np = test_df.to_numpy(dtype=object)[0:]
# test_np = test_np[:, 1:] # Remove id
# test_np_labels = test_df.columns.values
# test_np

In [52]:
# def calculate_gini(data):
#     true_val = data[data[:, test_np.shape[1]-1] == 1]
#     false_val = data[data[:, test_np.shape[1]-1] == 0]

#     return 1 - (len(true_val)/len(data))**2 - (len(false_val)/len(data))**2

In [53]:
# lowest_gini = float("inf")
# lowest_gini_feature = -1
# lowest_gini_threshold = -1

# for i in range(0, test_np.shape[1] - 1):
#     print(i)
#     print(np.unique(test_np[:, i]))

#     unique_values = np.unique(test_np[:, i])

#     # Calculate gini impurity
#     for j in range(unique_values.shape[0]-1):
#         filter_value = (unique_values[j]+unique_values[j+1])/2
#         print(filter_value)
    
#         left = test_np[test_np[:, i] >= filter_value]
#         right = test_np[test_np[:, i] < filter_value]
#         print(left)
#         print(right)
#         assert len(left) + len(right) == len(test_np)

#         total_gini_impurity = (len(left)/len(test_np))*calculate_gini(left) + (len(right)/len(test_np))*calculate_gini(right)
#         print(total_gini_impurity)

#         if total_gini_impurity < lowest_gini:
#             lowest_gini = total_gini_impurity
#             lowest_gini_feature = i
#             lowest_gini_threshold = filter_value


#     print()
#     print()

In [5]:
import pandas as pd

In [10]:
df = pd.read_csv("./data/final_dataset.csv")

In [11]:
df

,PLAYER_1,PLAYER_2,ATP_POINT_DIFF,ATP_RANK_DIFF,AGE_DIFF,HEIGHT_DIFF,BEST_OF,DRAW_SIZE,H2H_DIFF,H2H_SURFACE_DIFF,DIFF_N_GAMES,WIN_LAST_3_DIFF,WIN_LAST_5_DIFF,WIN_LAST_10_DIFF,WIN_LAST_25_DIFF,WIN_LAST_50_DIFF,WIN_LAST_100_DIFF,P_ACE_LAST_3_DIFF,P_DF_LAST_3_DIFF,P_1ST_IN_LAST_3_DIFF,P_1ST_WON_LAST_3_DIFF,P_2ND_WON_LAST_3_DIFF,P_BP_SAVED_LAST_3_DIFF,P_ACE_LAST_5_DIFF,P_DF_LAST_5_DIFF,P_1ST_IN_LAST_5_DIFF,P_1ST_WON_LAST_5_DIFF,P_2ND_WON_LAST_5_DIFF,P_BP_SAVED_LAST_5_DIFF,P_ACE_LAST_10_DIFF,P_DF_LAST_10_DIFF,P_1ST_IN_LAST_10_DIFF,P_1ST_WON_LAST_10_DIFF,P_2ND_WON_LAST_10_DIFF,P_BP_SAVED_LAST_10_DIFF,P_ACE_LAST_20_DIFF,P_DF_LAST_20_DIFF,P_1ST_IN_LAST_20_DIFF,P_1ST_WON_LAST_20_DIFF,P_2ND_WON_LAST_20_DIFF,P_BP_SAVED_LAST_20_DIFF,P_ACE_LAST_50_DIFF,P_DF_LAST_50_DIFF,P_1ST_IN_LAST_50_DIFF,P_1ST_WON_LAST_50_DIFF,P_2ND_WON_LAST_50_DIFF,P_BP_SAVED_LAST_50_DIFF,P_ACE_LAST_100_DIFF,P_DF_LAST_100_DIFF,P_1ST_IN_LAST_100_DIFF,P_1ST_WON_LAST_100_DIFF,P_2ND_WON_LAST_100_DIFF,P_BP_SAVED_LAST_100_DIFF,P_ACE_LAST_200_DIFF,P_DF_LAST_200_DIFF,P_1ST_IN_LAST_200_DIFF,P_1ST_WON_LAST_200_DIFF,P_2ND_WON_LAST_200_DIFF,P_BP_SAVED_LAST_200_DIFF,P_ACE_LAST_300_DIFF,P_DF_LAST_300_DIFF,P_1ST_IN_LAST_300_DIFF,P_1ST_WON_LAST_300_DIFF,P_2ND_WON_LAST_300_DIFF,P_BP_SAVED_LAST_300_DIFF,P_ACE_LAST_2000_DIFF,P_DF_LAST_2000_DIFF,P_1ST_IN_LAST_2000_DIFF,P_1ST_WON_LAST_2000_DIFF,P_2ND_WON_LAST_2000_DIFF,P_BP_SAVED_LAST_2000_DIFF,ELO_DIFF,ELO_SURFACE_DIFF,ELO_GRAD_5_DIFF,ELO_GRAD_10_DIFF,ELO_GRAD_20_DIFF,ELO_GRAD_35_DIFF,ELO_GRAD_50_DIFF,ELO_GRAD_100_DIFF,ELO_GRAD_250_DIFF,RESULT
0,101746.0,101142.0,-1028.0,69.0,-5.000000,-5.0,3,32,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.00,-0.00,-0.00,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-24.000000,-24.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-1.0
1,100587.0,101613.0,-257.0,126.0,10.300000,8.0,3,32,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.00,-0.00,-0.00,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-24.000000,-24.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-1.0
2,101179.0,101601.0,352.0,-135.0,3.700000,0.0,3,32,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
3,101117.0,101332.0,19.0,-7.0,2.000000,7.0,3,32,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
4,101901.0,101735.0,-734.0,162.0,-0.900000,-11.0,3,32,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95486,207989.0,104925.0,3110.0,-4.0,-15.953457,-5.0,5,128,-1.0,-2.0,-1033.0,-0.0,-0.0,-0.1,-0.12,0.04,-0.05,5.606295,-1.662195,-6.493292,4.925324,4.204545,-20.000000,4.677414,0.620253,-3.513337,-0.640947,2.106687,-24.500000,4.329239,-2.276022,-0.048940,0.483814,1.380846,-10.166667,0.184295,-1.556406,-0.503063,0.210491,-0.119946,3.160714,-1.900247,-0.373552,1.384393,-1.022281,0.585562,3.639035,-2.366506,-0.358958,1.571564,-2.931574,0.045840,3.757585,-3.448003,-0.164040,1.507824,-4.350004,-0.359814,2.592090,-3.528808,-0.331222,0.558347,-4.939640,-0.732755,-0.156113,-2.307914,-0.096955,0.296011,-2.422849,-0.447300,-1.415974,-93.297142,-175.699868,0.685904,-1.530670,-3.116970,-1.627271,1.600634,0.640399,1.578129,-1.0
95487,132283.0,210097.0,-1254.0,35.0,7.413415,-2.0,5,128,-0.0,-1.0,171.0,-0.0,0.2,-0.2,-0.16,-0.14,-0.13,3.408474,-1.288858,-5.069536,-1.140525,-1.197776,13.535354,-0.395247,-0.391637,-7.297042,-5.260655,-5.076783,1.454545,-4.191331,0.388035,-7.867986,-6.931146,-13.155896,-7.106061,-3.349879,-0.206393,-5.891423,-4.274586,-6.939392,-17.525832,-2.965356,-1.280109,-1.830101,-2.741635,-4.109549,-9.013380,-3.571754,-1.943936,-0.443063,-3.278590,-2.201887,-4.777766,-3.733690,-2.240103,0.754896,-3.451428,-2.625701,-6.033147,-3.662575,-2.156490,-0.472305,-3.126597,-2.624421,-5.712232,-3.662575,-2.156490,-0.472305,-3.126597,-2.624421,-5.712232,-148.049490,-154.666406,6.688210,2.921914,-3.477755,-2.555178,-1.863525,-2.386409,-0.000000,-1.0
95488,200282.0,206173.0,-8295.0,7.0,2.493498,-8.0,5,128,-9.0,-8.0,56.0,-0.0,-0.2,-0.5,-0.32,-0.26,-0.22,-1.931250,2.011506,-7.557611,-2.142773,-9.788109,-0.000000,-4.828748,1.848594,-2.774676,-8.158374,-12.650414,-3.571429,-7.667758,2.425633,-9.869676,-7.325321,-9.154555,-14.904762,-5.720971,2.688755,-9.023918,-6.324372,-8.966347,-23.562271,-5.854667,1.586977,-7.440707,-7.661580,-4.481145,-15.896265,-4.214030,1.162460,-6.665356,-7.009222,-4.817320,-14.573357,-3.852117,0.623248,-3.345767,-5.803974,-3.985871,-8.247141,-3.104864,0.417251,-1.731565,-4.725031,-3.188244,-8.934925,-2.640903,0.578925,-1.219465,-4.049694,-2.492889,-7.589218,-303.764362,-327.732540,3.868456,-5.110113,-4.547991,-3.631950,-1.387032,-0.508457,-0.613204,-1.0
95489,206173.0,210097.0,9550.0,-19.0,1.147844,-2.0,5,128,3.0,2.0,218.0,0.0,0.2,0.2,0.24,0.32,0.30,3.856558,-0.212808,-12.774315,1.454393,-5.388693,-2.020202,1.854746,0.006506,-12.195088,-1.001521,-2.628600,-21.212121,2.486898,-1.052271,-9.808098,-0.032961,-6.175285,2.227273,0.789903,-1.346735,-9.075170,0.838626,-1.360639,-0.871070,0.338347,-1.424771,-7.835782,3.374194,2.554033,1.438080,-1.371844,-2.187831,-5.145923,3.264626,3.991262,6.723795,-2.389454,-1.854925,-6.474448,1.782503,3.317072,-0.121297,-3.276262,-1.898582,-6.385050,0.207480,2.072214,-0.172324,-3.656704,-1.938023,-6.345517,-0.517787,1.528889,-1.029495,390.654026,391.699508,-7.701382,0.587323,0.523377,-0.573950,-0.148565,-0.492939,0.000000,1.0
95490,100644.0,206173.0,-4195.0,1.0,4.323066,7.0,5,128,2.0,2.0,304.0,-0.0,-0.0,-0.1,-0.16,-0.14,-0.15,1.601140,-0.682342,11.308906,2.789013,15.579806,38.888889,0.746477,0.215111,9.814434,3.181649,4.509606,39.333333,-1.313750,1.066124,4.510675,3.001598,5.774872,13.363636,0.612660,0.912461,7.088909,-0.455303,0.002858,-3.515984,1.567855,0.642723,7.732242,-0.256849,-1.314796,-3.089835,1.759709,0.279523,8.878451,-2.250824,-1.791038,-7.150992,2.102533,0.667007,10.829599,-2.175355,-4.107744,-2.677511,3.752182,1.268188,9.892142,-0.011215,-3.659254,-4.440009,3.290283,1.976584,6.451648,-0.528973,-4.040472,-4.523317,-217.404211,-241.229146,1.616586,2.362125,1.025873,-1.710844,-1.281236,-1.050292,-1.696856,-1.0

In [13]:
pd.set_option('display.max_columns', None)
df[((df["PLAYER_1"] == 207989) & (df["PLAYER_2"] == 104925)) | ((df["PLAYER_2"] == 207989) & (df["PLAYER_1"] == 104925))]

,PLAYER_1,PLAYER_2,ATP_POINT_DIFF,ATP_RANK_DIFF,AGE_DIFF,HEIGHT_DIFF,BEST_OF,DRAW_SIZE,H2H_DIFF,H2H_SURFACE_DIFF,DIFF_N_GAMES,WIN_LAST_3_DIFF,WIN_LAST_5_DIFF,WIN_LAST_10_DIFF,WIN_LAST_25_DIFF,WIN_LAST_50_DIFF,WIN_LAST_100_DIFF,P_ACE_LAST_3_DIFF,P_DF_LAST_3_DIFF,P_1ST_IN_LAST_3_DIFF,P_1ST_WON_LAST_3_DIFF,P_2ND_WON_LAST_3_DIFF,P_BP_SAVED_LAST_3_DIFF,P_ACE_LAST_5_DIFF,P_DF_LAST_5_DIFF,P_1ST_IN_LAST_5_DIFF,P_1ST_WON_LAST_5_DIFF,P_2ND_WON_LAST_5_DIFF,P_BP_SAVED_LAST_5_DIFF,P_ACE_LAST_10_DIFF,P_DF_LAST_10_DIFF,P_1ST_IN_LAST_10_DIFF,P_1ST_WON_LAST_10_DIFF,P_2ND_WON_LAST_10_DIFF,P_BP_SAVED_LAST_10_DIFF,P_ACE_LAST_20_DIFF,P_DF_LAST_20_DIFF,P_1ST_IN_LAST_20_DIFF,P_1ST_WON_LAST_20_DIFF,P_2ND_WON_LAST_20_DIFF,P_BP_SAVED_LAST_20_DIFF,P_ACE_LAST_50_DIFF,P_DF_LAST_50_DIFF,P_1ST_IN_LAST_50_DIFF,P_1ST_WON_LAST_50_DIFF,P_2ND_WON_LAST_50_DIFF,P_BP_SAVED_LAST_50_DIFF,P_ACE_LAST_100_DIFF,P_DF_LAST_100_DIFF,P_1ST_IN_LAST_100_DIFF,P_1ST_WON_LAST_100_DIFF,P_2ND_WON_LAST_100_DIFF,P_BP_SAVED_LAST_100_DIFF,P_ACE_LAST_200_DIFF,P_DF_LAST_200_DIFF,P_1ST_IN_LAST_200_DIFF,P_1ST_WON_LAST_200_DIFF,P_2ND_WON_LAST_200_DIFF,P_BP_SAVED_LAST_200_DIFF,P_ACE_LAST_300_DIFF,P_DF_LAST_300_DIFF,P_1ST_IN_LAST_300_DIFF,P_1ST_WON_LAST_300_DIFF,P_2ND_WON_LAST_300_DIFF,P_BP_SAVED_LAST_300_DIFF,P_ACE_LAST_2000_DIFF,P_DF_LAST_2000_DIFF,P_1ST_IN_LAST_2000_DIFF,P_1ST_WON_LAST_2000_DIFF,P_2ND_WON_LAST_2000_DIFF,P_BP_SAVED_LAST_2000_DIFF,ELO_DIFF,ELO_SURFACE_DIFF,ELO_GRAD_5_DIFF,ELO_GRAD_10_DIFF,ELO_GRAD_20_DIFF,ELO_GRAD_35_DIFF,ELO_GRAD_50_DIFF,ELO_GRAD_100_DIFF,ELO_GRAD_250_DIFF,RESULT
87971,104925.0,207989.0,4582.0,-8.0,16.000000,5.0,3,64,-0.0,-0.0,1072.0,-0.000000,-0.4,-0.2,-0.00,0.06,0.142727,0.948078,0.994104,-2.881098,-10.771559,-10.626632,3.174603,1.594690,1.581781,-3.153694,-12.732591,-10.772023,-3.095238,3.778173,1.239827,-3.060431,-4.840298,-6.024170,0.952381,4.068507,0.591150,-3.228102,-1.394513,1.608751,-4.010836,3.906552,0.639360,-0.838212,3.417449,-0.360336,4.974338,4.214478,0.464597,0.394571,4.884703,0.171898,6.957981,4.193129,0.346284,1.413104,5.855448,2.874747,7.387992,3.346290,0.306446,1.672855,4.993086,2.041127,6.866844,3.144801,0.043788,1.387702,3.631942,2.235044,7.335393,168.082874,242.298364,-9.824259,-12.184386,-9.467986,-5.653162,-3.717141,-0.000000,-0.000000,-1.0
91031,207989.0,104925.0,860.0,-2.0,-16.000000,-5.0,5,128,1.0,1.0,-1060.0,-0.000000,-0.0,-0.0,0.08,-0.02,-0.030000,-1.139440,-2.285771,6.185805,-1.367738,15.177734,1.309524,-2.280913,-1.218780,6.251846,-1.158680,11.311621,-4.547619,0.243818,-1.136515,3.648620,-0.342500,8.429367,5.336580,-2.143261,-1.427958,1.992413,-1.304283,3.112104,5.433622,-4.137485,-0.401911,1.798079,-6.701403,-1.278231,3.314475,-4.105460,-0.194249,1.356134,-4.553247,-0.748807,0.898604,-4.254314,-0.353084,0.147541,-5.571763,-0.914629,-2.622689,-3.806520,-0.246377,-0.402337,-5.328006,-1.637620,-2.012213,-2.876256,-0.070221,-0.008883,-3.022974,-0.914197,-2.751131,-113.754096,-93.910916,2.322475,-1.089552,5.806386,4.126001,2.382128,1.589692,-0.000000,-1.0
91328,207989.0,104925.0,80.0,-1.0,-16.000000,-5.0,5,128,0.0,0.0,-1056.0,0.000000,0.0,0.0,0.08,0.02,-0.040000,-5.140897,2.784855,1.511243,-2.510139,0.374270,-6.944444,-5.213164,2.881858,-0.561124,-6.334483,-3.331779,1.785714,-3.920402,1.486330,-1.836332,-2.595761,-3.361752,2.142857,-1.625570,0.359154,1.624132,-2.205135,-0.083134,4.317100,-3.537167,-0.171376,0.915082,-5.489309,-0.714979,7.021861,-3.688495,0.020839,1.049927,-4.317346,-1.407104,4.431898,-4.080172,-0.225569,-0.047157,-5.321223,-1.132477,-1.628817,-3.810558,-0.201154,-0.335905,-5.308838,-1.850481,-1.551593,-2.776299,-0.040290,0.004498,-2.804359,-1.019571,-1.818633,-56.843073,-312.511598,2.711180,0.534606,1.122053,3.603520,2.894884,1.297982,0.000000,1.0
91645,207989.0,104925.0,600.0,-1.0,-16.000000,-5.0,3,64,1.0,-0.0,-1053.0,-0.000000,-0.0,-0.0,0.04,0.02,-0.030000,0.041420,2.386249,-0.237625,0.439822,-1.353792,-27.061404,-3.575823,2.377910,-0.472027,-6.720172,-4.322742,-16.236842,-3.210440,1.934031,-2.498315,-3.109994,-1.138677,-1.058897,-1.665612,0.788119,-0.220108,-0.997805,-0.288513,2.553885,-3.388386,-0.102768,0.539306,-5.177913,-0.737177,7.481511,-3.388524,0.049352,0.944479,-4.323089,-1.292257,3.814500,-4.026445,-0.205925,-0.075648,-5.307622,-1.028193,-1.744391,-3.775489,-0.182608,-0.418668,-5.313239,-1.832002,-1.738804,-2.758350,-0.023066,-0.074682,-2.822365,-0.998029,-1.825170,-92.860728,-272.111776,-2.516568,1.419867,1.274740,3.549330,2.965849,1.299008,-0.000000,-1.0
92333,104925.0,207989.0,1490.0,-1.0,15.900000,5.0,3,8,0.0,1.0,1052.0,0.333333,0.4,0.4,0.20,0.06,0.060000,10.999507,1.366845,-3.427161,13.281530,5.258981,21.428571,9.802158,0.844558,-4.692497,8.908585,7.065768,15.523810,7.122943,1.353619,-4.231690,10.448715,3.937820,2.237013,3.831500,1.196261,-4.145335,7.675955,2.000636,-1.146688,3.042229,0.732972,-1.986219,4.702283,0.394392,-1.427362,3.423397,0.070948,-1.599300,5.800555,1.482060,-4.210420,4.013695,0.315058,-0.590720,5.587973,0.763427,0.713262,3.732200,0.243593,-0.118018,5.440136,1.895683,1.360761,2.752032,0.029691,-0.009684,2.986772,1.009100,1.988248,185.052475,312.720611,9.330780,7.836640,3.918734,1.752692,-0.741560,-1.177663,0.000000,1.0
94137,104925.0,207989.0,230.0,-1.0,16.000000,5.0,5,128,1.0,-1.0,1046.0,-0.000000,-0.0,0.1,-0.08,0.06,0.040000,2.442315,0.381111,3.804921,10.942316,3.254491,26.153846,2.253924,0.252089,2.815184,10.134194,3.375715,8.358974,0.774676,-0.389890,1.671134,4.449919,1.546557,1.522276,1.926291,0.137693,-1.932314,3.164592,-0.157467,-0.952746,4.143532,0.048459,-3.882244,5.952123,1.259874,-4.126678,3.361319,0.211743,-1.959297,5.612999,0.984835,-6.484389,3.618927,0.126134,-1.490879,4.775793,0.182909,-2.448872,3.864213,0.261493,-0.615774,5.424531,0.943769,0.334821,2.670611,0.031661,-0.402520,3.040578,0.847300,1.670075,13.198497,234.727000,-3.257391,0.660418,-4.297481,-5.112747,-2.432403,-0.580454,-0.000000,-1.0
94433,207989.0,104925.0,-330.0,1.0,-15.900000,-5.0,3,64,-0.0,-0.0,-1045.0,-0.000000,0.2,0.1,0.12,-0.00,-0.020000,0.537759,2.181601,-2.133458,5.091205,-17.459861,4.444444,0.032823,0.951279,2.444207,3.359716,0.997768,16.476190,-2.070721,0.710903,-0.912373,-3.157647,-1.660769,4.058608,-1.082755,0.473786,1.104918,-0.942822,-0.279876,3.232133,-3.739622,0.268969,2.949734,-4.155712,-0.638206,6.626553,-3.288675,-0.192377,2.026429,-4.916303,-0.548102,6.697087,-3.582053,-0.028867,1.574035,-4.488779,-0.497144,2.846491,-3.808307,-0.234522,0.649700,-5.280599,-0.879872,-0.135419,-2.606380,-0.021915,0.447588,-2.900936,-0.720841,-1.447153,-38.545923,-86.320746,-0.672534,4.596072,2.525577,5.021056,3.803176,0.737636,-0.000000,-1.0
95486,207989.0,104925.0,3110.0,-4.0,-15.953457,-5.0,5,128,-1.0,-2.0,-1033.0,-0.000000,-0.0,-0.1,-0.12,0.04,-0.050000,5.606295,-1.662195,-6.493292,4.925324,4.204545,-20.000000,4.677414,0.620253,-3.513337,-0.640947,2.106687,-24.500000,4.329239,-2.276022,-0.048940,0.483814,1.380846,-10.166667,0.184295,-1.556406,-0.503063,0.210491,-0.119946,3.160714,-1.900247,-0.373552,1.384393,-1.022281,0.585562,3.639035,-2.366506,-0.358958,1.571564,-2.931574,0.045840,3.757585,-3.448003,-0.164040,1.507824,-4.350004,-0.359814,2.592090,-3.528808,-0.331222,0.558347,-4.939640,-0.732755,-0.156113,-2.307914,-0.096955,0.296011,-2.422849,-0.447300,-1.415974,-93.297142,-175.699868,0.685904,-1.530670,-3.116970,-1.627271,1.600634,0.640399,1.578129,-1.0